# Generated by Django 4.1.6 on 2023-02-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='KolBasicData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=500)),
                ('platform', models.CharField(max_length=20)),
                ('followers', models.BigIntegerField()),
                ('desc', models.CharField(max_length=1000)),
                ('avatarurl', models.URLField()),
            ],
        ),
    ]
