# Generated by Django 4.1.6 on 2023-06-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kol', '0002_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='kw_original',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
