# Generated by Django 4.1.6 on 2023-06-14 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kol', '0003_brand_kw_original'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
