# Generated by Django 4.1.6 on 2023-06-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kol', '0004_delete_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=200)),
                ('origin', models.CharField(max_length=200)),
                ('segment', models.CharField(max_length=200)),
                ('kw_original', models.TextField()),
                ('kw_formatted', models.TextField()),
            ],
        ),
    ]
