# Generated by Django 4.1.6 on 2023-06-17 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kol', '0005_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('attribute_id', models.AutoField(primary_key=True, serialize=False)),
                ('layer_1', models.CharField(max_length=200)),
                ('layer_2', models.CharField(max_length=200)),
                ('layer_3', models.CharField(max_length=200)),
                ('layer_4', models.CharField(max_length=200)),
                ('kw_original', models.TextField()),
                ('kw_formatted', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('hero_product', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('product_series', models.CharField(max_length=200)),
                ('kw_original', models.TextField()),
                ('kw_formatted', models.TextField()),
                ('brand_id', models.ForeignKey(db_column='brand_id', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='kol.brand')),
            ],
        ),
        migrations.DeleteModel(
            name='Kol',
        ),
        migrations.DeleteModel(
            name='KolBasicData',
        ),
    ]
