# Generated by Django 4.1.6 on 2023-06-17 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kol', '0006_attribute_product_delete_kol_delete_kolbasicdata'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together={('attribute_id', 'layer_4')},
        ),
    ]
